set_data:
  description: Set Ariston Data via HTTP
  fields:
    entity_id:
      description: "(Mandatory) Climate 'enity_id' for Ariston heater"
      example: climate.ariston
    mode:
      description: "(Optional) General mode: 'Winter' or 'Summer' or 'Off' or other. Values depend on model (see 'options_text' attributes in corresponding sensors)."
      example: Winter
    ch_auto_function:
      description: "(Optional) CH AUTO function ('ON' or 'OFF')"
      example: "ON"
    ch_mode_zone1:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_mode_zone2:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_mode_zone3:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_mode_zone4:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_mode_zone5:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_mode_zone6:
      description: "(Optional) CH mode: 'Manual' or 'Time program'."
      example: "Time program"
    ch_set_temperature_zone1:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_set_temperature_zone2:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_set_temperature_zone3:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_set_temperature_zone4:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_set_temperature_zone5:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_set_temperature_zone6:
      description: "(Optional) Set currently used CH temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone1:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone2:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone3:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone4:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone5:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_comfort_temperature_zone6:
      description: "(Optional) Set CH Comfort temperature in steps of '0.5'. Value range depends on model."
      example: 23
    ch_economy_temperature_zone1:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_economy_temperature_zone2:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_economy_temperature_zone3:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_economy_temperature_zone4:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_economy_temperature_zone5:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_economy_temperature_zone6:
      description: "(Optional) Set CH Economy temperature in steps of '0.5'. Value range depends on model."
      example: 23.5
    ch_water_temperature:
      description: "(Optional) Set CH water temperature in steps of '1.0'. Value range depends on model."
      example: 80
    ch_fixed_temperature:
      description: "(Optional) Set CH fixed water temperature in steps of '1.0'. Value range depends on model."
      example: -4
    dhw_mode:
      description: "(Optional) CH mode: 'Disabled' or 'Time Based' or 'Always active'."
      example: "Time Based"
    dhw_comfort_function:
      description: "(Optional) DHW Comfort Function: 'Disabled' or 'Time Based' or 'Always active'"
      example: "Time Based"
    dhw_set_temperature:
      description: "(Optional) Set currently used DHW temperature in steps of '1.0'. Value range depends on model."
      example: 46
    dhw_comfort_temperature:
      description: "(Optional) Set DHW Comfort temperature in steps of '1.0'. Value range depends on model."
      example: 46
    dhw_economy_temperature:
      description: "(Optional) Set DHW Economy temperature in steps of '1.0'. Value range depends on model."
      example: 46
    dhw_thermal_cleanse_cycle:
      description: "(Optional) Thermal Cleanse Cycle in hours."
      example: 240
    dhw_thermal_cleanse_function:
      description: "(Optional) Thermal Cleanse Function ('ON' or 'OFF')."
      example: "ON"
    internet_time:
      description: "(Optional) enable or disable time from internet ('ON' or 'OFF')."
      example: "ON"
    internet_weather:
      description: "(Optional) enable or disable weather from internet ('ON' or 'OFF')."
      example: "ON"
